osx_image: xcode7.2
language: objective-c

before_install:
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean test --project SwiftMime.xcodeproj -scheme "SwiftMime" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
